version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend/app:/app/app
      - ./packages/frontend/public:/app/public
    command: npm run dev
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile 
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app
    command: npm run start:dev